# Generated by Django 5.0.7 on 2024-07-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='location',
            field=models.CharField(default='nairobi', max_length=20),
        ),
    ]
